kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app: ping-cloud

resources:
- pingdatagovernance-ingress.yaml
- pingfederate-ingress.yaml
- pingdataconsole-ingress.yaml
